name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs: Lancement avec Ubuntu
  check-bats-version:
    runs-on: ubuntu-latest

    steps1: 
      - uses: actions/checkout@v6

    steps2:  Récupérer le code du dépôt 
      - uses: actions/setup-node@v4

       step3:  Installer Node.js 
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
step4:  Lancer les tests automatisés avec 
- run: npm test 
